Update for Odin
cassidyjames/dippi pull request #80
Opened 2021-02-25 21:40 UTC by cassidyjames

Yay!

2021-02-25 21:41 UTC, jackpot51 approved these changes

2021-02-27 07:14 UTC, meisenzahl requested changes

2021-02-27 07:14 UTC, meisenzahl commented on src/MainWindow.vala
> +           show_close_button = true
```suggestion
           show_close_button = true,
           title = _("Dippi")
```

In case you want to keep the title in the header :)

2021-02-27 07:14 UTC, meisenzahl commented on meson.build
> +    dependency('libhandy-1', version: '>=1.0.0'),
Don't forget to also update `deb-packaging` branch once you are done and add `libhandy-1-dev (>= 1.0.0),` to `debian/control`.

2021-04-21 21:53 UTC, merged